# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyUtilSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase', '>= 2.5.1’
    pod 'Firebase/Core'
    pod 'Firebase/Auth’
    pod 'Firebase/Messaging'
  # Pods for MyUtilSwift

end
